name: master

on:
  push:
    branches:
      - main # master 브랜치에서 push 이벤트가 일어났을 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get Secrets by Name and by ARN
        id: aws-secret
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            dev/test

      - name: Build
        run: npm run build
        env:
          REACT_APP_CORS_URL: ${{ steps.aws-secret.outputs }}

      - name: Create .env file
        run: |
          touch .env   
          echo "${{ steps.aws-secret.outputs }}" >> .env

      # - name: Deploy to S3
      #   run: aws s3 sync build/ s3://${{ secrets.S3_BUCKET_ID }} --delete

      # - name: Invalidate CloudFront Cache
      #   run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
