name: master

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get SSM Parameters
        id: ssm
        run: |
          REACT_APP_CORS_URL=$(aws ssm get-parameter --name "/test/hhj/REACT_APP_CORS_URL" --with-decryption --query "Parameter.Value" --output text)
          S3_BUCKET_ID=$(aws ssm get-parameter --name "/test/hhj/S3_BUCKET_ID" --with-decryption --query "Parameter.Value" --output text)
          DISTRIBUTION_ID=$(aws ssm get-parameter --name "/test/hhj/DISTRIBUTION_ID" --with-decryption --query "Parameter.Value" --output text)
          echo "REACT_APP_CORS_URL=$REACT_APP_CORS_URL" >> $GITHUB_ENV
          echo "S3_BUCKET_ID=$S3_BUCKET_ID" >> $GITHUB_ENV
          echo "DISTRIBUTION_ID=$DISTRIBUTION_ID" >> $GITHUB_ENV

      - name: Build
        run: npm run build
        env:
          REACT_APP_CORS_URL: ${{ env.REACT_APP_CORS_URL }}

      - name: Deploy to S3
        env:
          S3_BUCKET_ID: ${{ env.S3_BUCKET_ID }}
        run: aws s3 sync build/ s3://${{ env.S3_BUCKET_ID }} --delete

      - name: Invalidate CloudFront Cache
        env:
          DISTRIBUTION_ID: ${{ env.DISTRIBUTION_ID }}
        run: aws cloudfront create-invalidation --distribution-id ${{ env.DISTRIBUTION_ID }} --paths "/*"
